# Тема 10. Введение в ООП
Отчет по Теме #10 выполнил(а):
- Соломин Владислав Алексеевич
- ИНО ОЗБ ПОАС 22-1

| Задание | Сам_раб |
| ------ |-----|
| Задание 1 | + | 
| Задание 2 | + | 
| Задание 3 | + | 
| Задание 4 | + | 
| Задание 5 | + | 

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор. Подсказка: необходимо использовать модуль time Декоратор необходимо использовать для этой функции:
![Меню](https://github.com/Riko-admin/education/blob/Тема_10/pic/1.png)
### Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы. Также на этом примере можете посмотреть, что решение задач через рекурсию не всегда является хорошей идеей. Поскольку решение Фибоначчи для 100 с использованием рекурсии и без динамического программирования решается более десяти секунд, а решение точно такой же задачи, но через цикл for еще и для 200, занимает меньше 1 секунды.
```python
import time
def timer(func):
    def wrapper():
        start_time =time.time();
        func()
        print()
        print(f"Затраченное время = {time.time()-start_time} секунд")
    return wrapper
@timer
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(f"Фибоначчи= {fib2}")
if __name__ == '__main__':
    fibonacci()
```
### Результат.
![Меню](https://github.com/Riko-admin/education/blob/Тема_10/pic/2.png)

## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.
```python
def read_file_content(filename):
    try:
        with open(filename, 'r') as file:
            content = file.read().strip()
            if not content:
                raise ValueError("файл пустой")
            return content
    except FileNotFoundError:
        print(f"Файл {filename} не найден.")
    except ValueError as e:
        print(e)
with open('text.txt', 'w') as file:
    pass
with open('text2.txt', 'w') as file:
    file.write("Всем привет!!!")
print(read_file_content('text.txt'))
print(read_file_content('text2.txt'))
```
### Результат.
![Меню](https://github.com/Riko-admin/education/blob/Тема_10/pic/3.png)

## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.
```python
def add_two_Input():
    try:
        personNumber = int(input("Введите число: "))
        print(f"Результат сложения: 2 + {personNumber} = {2 + personNumber}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")
add_two_Input()
```
### Результат.
![Меню](https://github.com/Riko-admin/education/blob/Тема_10/pic/4.png)

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
```python
class CacheResult:
    def __init__(self, func):
        self.func = func
        self.cache = {}
    def __call__(self, *args):
        if args not in self.cache:
            self.cache[args] = self.func(*args)
        return self.cache[args]
@CacheResult
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)
print(fibonacci(10))  # Вычисление
print(fibonacci(10))  # Из кэша
print(fibonacci(5))   # Вычисление
print(fibonacci(5))   # Из кэша
```
### Результат.
![Меню](https://github.com/Riko-admin/education/blob/Тема_10/pic/5.png)

## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
```python
class NegativeValueError(ValueError):
    def __init__(self, message="Значение не может быть отрицательным"):
        super().__init__(message)
def calculate_square_root(number):
    if number < 0:
        raise NegativeValueError
    return number * 0.5
def calculate_area(width, height):
    if width < 0 or height < 0:
        raise NegativeValueError("Ширина и высота должны быть положительными значениями")
    return width * height
# Пример 1:
try:
    result = calculate_square_root(-4)
    print(result)
except NegativeValueError as e:
    print(f"Ошибка: {e}")

# Пример 2:
try:
    area = calculate_area(5, -2)
    print(area)
except NegativeValueError as e:
    print(f"Ошибка: {e}")

```
### Результат.
![Меню](https://github.com/Riko-admin/education/blob/Тема_10/pic/6.png)
